apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomizezpc
  name: kustomizezpc
  namespace: kustomizezpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kustomizezpc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kustomizezpc
    spec:
      containers:
      - image: willguibr/kustomizezpc:0.1
        name: kustomizezpc
        resources: {}


