apiVersion: v1
kind: Service
metadata:
  labels:
    app: kustomizezpc
  name: goatlb
  namespace: kustomizezpc
spec:
  ports:
  - name: goatport
    protocol: TCP
    targetPort: 8080
    port: 80
  selector:
    app: kustomizezpc
  type: LoadBalancer
