apiVersion: v1
kind: Service
metadata:
  labels:
    app: kustomizezpc
  name: zpclb
  namespace: kustomizezpc
spec:
  ports:
  - name: zpcport
    protocol: TCP
    targetPort: 80
    port: 80
  selector:
    app: kustomizezpc
  type: LoadBalancer
status:
  loadBalancer: {}

